
---Alias for booleans
---@alias bool 
---|>' true' # 
---| ' false' # 

--- Alias used in function Image:GetChanSize(channel) end in fuse_api
---@alias channel 
---|>'<channel>' # 

--- Alias used for Tools in FuRegisterClass
---@alias toolType 
---|>' CT_Tool' 
---| ' CT_ParticleTool'
---| ' CT_SourceTool'
---| ' CT_Modifier'
---| ' CT_ViewLUTPlugin'

---@alias inputControls 
---|>' "ButtonControl"'
---| ' "CheckboxControl"'
---| ' "ColorControl"'
---| ' "ComboControl" '
---| ' "ComboIDControl" '
---| ' "FileControl" '
---| ' "FontFileControl" '
---| ' "GradientControl" '
---| ' "LabelControl"'
---| ' "MultiButtonControl" '
---| ' "MultiButtonIDControl" '
---| ' "OffsetControl" '
---| ' "RangeControl" '
---| ' "ScrewControl" '
---| ' "SliderControl" '
---| ' "TextEditControl"'

---@alias previewControls
---|>' "ButtonControl"'
---| ' "AngleControl"'
---| ' "CrossHairControl"'
---| ' "ImgOverlayControl"'
---| ' "RectangleControl"'
---| ' "PointControl"'
---| ' "TransformControl"'

---@alias alignment 
---|>' "Left"'
---| ' "CenteredLeft"
---| ' "Center" 
---| ' "CenteredRight"
---| ' "Right"
 
---@alias linkDataType 
---|>' "Clip"'
---| ' "Copy"'
---| ' "Image"'	
---| ' "Number"'	
---| ' "Particles"'	
---| ' "Point"'	
---| ' "Text"'	
---| ' "GetData"'	
---| ' "SetData"'	
---| ' "InterpolateWith"'

---@alias ChannelOpOfOperation
---|>' "Copy"'
---|' "Add"'
---|' "Subtract"'
---|' "Multiply"'
---|' "Divide"'
---|' "Max"'
---|' "Min"'
---|' "Invert"'
---|' "Difference"'
---|' "SignedAdd"'
---|' "Threshold"'

---@alias ColorSpace
---| ' "RGB"'
---| ' "HLS"'
---| ' "YUV"'
---| ' "YIQ"'
---| ' "CMY"'
---| ' "HSV"'
---| ' "XYZ"'
---| ' "LAB"'

---@alias ChannelOpOfChannels
---| ' Fg.R'
---| ' Fg.G'
---| ' Fg.B'
---| ' Fg.A'
---| ' Fg.Z
---| ' Fg.Coverage'
---| ' Fg.U'
---| ' Fg.V'
---| ' Fg.NX'
---| ' Fg.NY'
---| ' Fg.NZ'
---| ' Fg.BgR'
---| ' Fg.BgG'
---| ' Fg.BgB'
---| ' Fg.BgA'
---| ' Fg.ObjectID'
---| ' Fg.MaterialID'
---| ' Fg.VectX'
---| ' Fg.VectY'
---| ' Fg.BackVectX'
---| ' Fg.BackVectY'
---| ' Fg.HLS.H'
---| ' Fg.HLS.L'
---| ' Fg.HLS.S'
---| ' Fg.YUV.Y'
---| ' Fg.YUV.U'
---| ' Fg.YUV.V'
---| ' Fg.PositionX '
---| ' Fg.PositionY '
---| ' Fg.PositionZ '
---| ' Fg.DisparityX '
---| ' Fg.DisparityY '
---| ' Bg.R'
---| ' Bg.G'
---| ' Bg.B'
---| ' Bg.A'
---| ' Bg.Z
---| ' Bg.Coverage'
---| ' Bg.U'
---| ' Bg.V'
---| ' Bg.NX'
---| ' Bg.NY'
---| ' Bg.NZ'
---| ' Bg.BgR'
---| ' Bg.BgG'
---| ' Bg.BgB'
---| ' Bg.BgA'
---| ' Bg.ObjectID'
---| ' Bg.MaterialID'
---| ' Bg.VectX'
---| ' Bg.VectY'
---| ' Bg.BackVectX'
---| ' Bg.BackVectY'
---| ' Bg.HLS.H'
---| ' Bg.HLS.L'
---| ' Bg.HLS.S'
---| ' Bg.YUV.Y'
---| ' Bg.YUV.U'
---| ' Bg.YUV.V'
---| ' Bg.PositionX '
---| ' Bg.PositionY '
---| ' Bg.PositionZ '
---| ' Bg.DisparityX '
---| ' Bg.DisparityY '